/tasmania/doc/source/api.rst:1: WARNING: Title overline too short.

=================
Computational domain
=================
/tasmania/doc/source/api.rst:28: WARNING: autodoc: failed to import class 'Adjustment' from module 'tasmania.parameterizations.adjustments'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named 'tasmania.parameterizations'
/tasmania/doc/source/api.rst:31: WARNING: autodoc: failed to import class 'SlowTendency' from module 'tasmania.parameterizations.slow_tendencies'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named 'tasmania.parameterizations'
/tasmania/doc/source/api.rst:34: WARNING: autodoc: failed to import class 'FastTendency' from module 'tasmania.parameterizations.fast_tendencies'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named 'tasmania.parameterizations'
/tasmania/doc/source/api.rst:40: WARNING: autodoc: failed to import class 'AdjustmentMicrophysics' from module 'tasmania.parameterizations.adjustments'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named 'tasmania.parameterizations'
/tasmania/doc/source/api.rst:43: WARNING: autodoc: failed to import class 'AdjustmentMicrophysicsKesslerWRF' from module 'tasmania.parameterizations.adjustment_microphysics_kessler_wrf'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named 'tasmania.parameterizations'
/tasmania/doc/source/api.rst:46: WARNING: autodoc: failed to import class 'AdjustmentMicrophysicsKesslerWRFSaturation' from module 'tasmania.parameterizations.adjustment_microphysics_kessler_wrf_saturation'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named 'tasmania.parameterizations'
/tasmania/doc/source/api.rst:49: WARNING: autodoc: failed to import class 'SlowTendencyMicrophysics' from module 'tasmania.parameterizations.slow_tendencies'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named 'tasmania.parameterizations'
/tasmania/doc/source/api.rst:52: WARNING: autodoc: failed to import class 'SlowTendencyMicrophysicsKesslerWRF' from module 'tasmania.parameterizations.slow_tendency_microphysics_kessler_wrf'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named 'tasmania.parameterizations'
/tasmania/doc/source/api.rst:55: WARNING: autodoc: failed to import class 'SlowTendencyMicrophysicsKesslerWRFSaturation' from module 'tasmania.parameterizations.slow_tendency_microphysics_kessler_wrf_saturation'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named 'tasmania.parameterizations'
/tasmania/doc/source/api.rst:61: WARNING: autodoc: failed to import class 'GridData' from module 'tasmania.storages.grid_data'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named 'tasmania.storages'
/tasmania/doc/source/api.rst:64: WARNING: autodoc: failed to import class 'StateIsentropic' from module 'tasmania.storages.state_isentropic'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named 'tasmania.storages'
/tasmania/doc/source/api.rst:75: WARNING: missing attribute __cinit__ in object tasmania.grids.parser.parser_1d.Parser1d
docstring of tasmania.grids.parser.parser_1d.Parser1d:0: WARNING: duplicate object description of tasmania.grids.parser.parser_1d.Parser1d, other instance in /tasmania/doc/source/domain.rst, use :noindex: for one of them
docstring of tasmania.grids.parser.parser_1d.Parser1d.evaluate:0: WARNING: duplicate object description of tasmania.grids.parser.parser_1d.Parser1d.evaluate, other instance in /tasmania/doc/source/domain.rst, use :noindex: for one of them
/tasmania/doc/source/api.rst:78: WARNING: missing attribute __cinit__ in object tasmania.grids.parser.parser_2d.Parser2d
docstring of tasmania.grids.parser.parser_2d.Parser2d:0: WARNING: duplicate object description of tasmania.grids.parser.parser_2d.Parser2d, other instance in /tasmania/doc/source/domain.rst, use :noindex: for one of them
docstring of tasmania.grids.parser.parser_2d.Parser2d.evaluate:0: WARNING: duplicate object description of tasmania.grids.parser.parser_2d.Parser2d.evaluate, other instance in /tasmania/doc/source/domain.rst, use :noindex: for one of them
/tasmania/doc/source/api.rst:97: WARNING: autodoc: failed to import module 'tasmania.utils.utils_meteo'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named 'tasmania.utils.utils_meteo'
/tasmania/doc/source/api.rst:103: WARNING: autodoc: failed to import module 'tasmania.utils.utils_plot'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named 'tasmania.utils.utils_plot'
/tasmania/tasmania/grids/topography.py:docstring of tasmania.grids.topography.Topography1d:25: WARNING: Unexpected section title.

Attributes
----------
/tasmania/doc/source/domain.rst:11: WARNING: missing attribute __cinit__ in object tasmania.grids.parser.parser_1d.Parser1d
docstring of tasmania.grids.parser.parser_1d.Parser1d:0: WARNING: duplicate object description of tasmania.grids.parser.parser_1d.Parser1d, other instance in /tasmania/doc/source/api.rst, use :noindex: for one of them
docstring of tasmania.grids.parser.parser_1d.Parser1d.evaluate:0: WARNING: duplicate object description of tasmania.grids.parser.parser_1d.Parser1d.evaluate, other instance in /tasmania/doc/source/api.rst, use :noindex: for one of them
/tasmania/tasmania/grids/topography.py:docstring of tasmania.grids.topography.Topography2d:30: WARNING: Unexpected section title.

Reference
---------
/tasmania/tasmania/grids/topography.py:docstring of tasmania.grids.topography.Topography2d:34: WARNING: Unexpected section title.

Attributes
----------
/tasmania/doc/source/domain.rst:17: WARNING: missing attribute __cinit__ in object tasmania.grids.parser.parser_2d.Parser2d
docstring of tasmania.grids.parser.parser_2d.Parser2d:0: WARNING: duplicate object description of tasmania.grids.parser.parser_2d.Parser2d, other instance in /tasmania/doc/source/api.rst, use :noindex: for one of them
docstring of tasmania.grids.parser.parser_2d.Parser2d.evaluate:0: WARNING: duplicate object description of tasmania.grids.parser.parser_2d.Parser2d.evaluate, other instance in /tasmania/doc/source/api.rst, use :noindex: for one of them
/tasmania/doc/source/domain.rst:3: WARNING: Duplicate explicit target name: "cosmo model".
/tasmania/tasmania/dynamics/dycore.py:docstring of tasmania.dynamics.dycore.DynamicalCore.output_properties:0: WARNING: Definition list ends without a blank line; unexpected unindent.
/tasmania/tasmania/dynamics/dycore.py:docstring of tasmania.dynamics.dycore.DynamicalCore.output_properties:8: WARNING: Definition list ends without a blank line; unexpected unindent.
/tasmania/tasmania/dynamics/dycore.py:docstring of tasmania.dynamics.dycore.DynamicalCore.update_topography:0: WARNING: Definition list ends without a blank line; unexpected unindent.
/tasmania/doc/source/dynamics.rst:17: WARNING: autodoc: failed to import class 'HorizontalVelocity' from module 'tasmania.dynamics'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sphinx/util/inspect.py", line 169, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'tasmania.dynamics' has no attribute 'HorizontalVelocity'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 665, in import_object
    obj = self.get_attr(obj, part)
  File "/usr/local/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 554, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/usr/local/lib/python3.5/site-packages/sphinx/util/inspect.py", line 185, in safe_getattr
    raise AttributeError(name)
AttributeError: HorizontalVelocity
/tasmania/doc/source/dynamics.rst:20: WARNING: autodoc: failed to import class 'WaterConstituent' from module 'tasmania.dynamics'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sphinx/util/inspect.py", line 169, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'tasmania.dynamics' has no attribute 'WaterConstituent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 665, in import_object
    obj = self.get_attr(obj, part)
  File "/usr/local/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 554, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/usr/local/lib/python3.5/site-packages/sphinx/util/inspect.py", line 185, in safe_getattr
    raise AttributeError(name)
AttributeError: WaterConstituent
/tasmania/tasmania/dynamics/isentropic_prognostic.py:docstring of tasmania.dynamics.isentropic_prognostic.IsentropicPrognostic.__init__:4: WARNING: Unexpected section title.

Parameters
----------
/tasmania/tasmania/dynamics/isentropic_prognostic.py:docstring of tasmania.dynamics.isentropic_prognostic.IsentropicPrognostic.__init__:49: WARNING: Block quote ends without a blank line; unexpected unindent.
/tasmania/tasmania/dynamics/isentropic_prognostic.py:docstring of tasmania.dynamics.isentropic_prognostic.IsentropicPrognostic.factory:5: WARNING: Unexpected section title.

Parameters
----------
/tasmania/tasmania/dynamics/isentropic_prognostic.py:docstring of tasmania.dynamics.isentropic_prognostic.IsentropicPrognostic.factory:56: WARNING: Block quote ends without a blank line; unexpected unindent.
/tasmania/tasmania/dynamics/isentropic_prognostic.py:docstring of tasmania.dynamics.isentropic_prognostic.IsentropicPrognostic.factory:69: WARNING: Unexpected section title.

Return
------
/tasmania/tasmania/dynamics/isentropic_prognostic.py:docstring of tasmania.dynamics.isentropic_prognostic.IsentropicPrognostic.step_integrating_sedimentation_flux:9: WARNING: Unexpected section title.

Parameters
----------
/tasmania/tasmania/dynamics/isentropic_prognostic.py:docstring of tasmania.dynamics.isentropic_prognostic.IsentropicPrognostic.step_integrating_sedimentation_flux:14: WARNING: Definition list ends without a blank line; unexpected unindent.
/tasmania/tasmania/dynamics/isentropic_prognostic.py:docstring of tasmania.dynamics.isentropic_prognostic.IsentropicPrognostic.step_integrating_sedimentation_flux:15: WARNING: Block quote ends without a blank line; unexpected unindent.
/tasmania/tasmania/dynamics/isentropic_prognostic.py:docstring of tasmania.dynamics.isentropic_prognostic.IsentropicPrognostic.step_integrating_sedimentation_flux:25: WARNING: Block quote ends without a blank line; unexpected unindent.
/tasmania/tasmania/dynamics/isentropic_prognostic.py:docstring of tasmania.dynamics.isentropic_prognostic.IsentropicPrognostic.step_integrating_sedimentation_flux:30: WARNING: Unexpected indentation.
/tasmania/tasmania/dynamics/isentropic_prognostic.py:docstring of tasmania.dynamics.isentropic_prognostic.IsentropicPrognostic.step_integrating_sedimentation_flux:41: WARNING: Unexpected section title.

Return
------
/tasmania/tasmania/dynamics/isentropic_prognostic.py:docstring of tasmania.dynamics.isentropic_prognostic.IsentropicPrognostic.step_integrating_sedimentation_flux:42: WARNING: Block quote ends without a blank line; unexpected unindent.
/tasmania/tasmania/dynamics/isentropic_prognostic.py:docstring of tasmania.dynamics.isentropic_prognostic.IsentropicPrognostic.step_integrating_vertical_advection:8: WARNING: Unexpected section title.

Parameters
----------
/tasmania/tasmania/dynamics/isentropic_prognostic.py:docstring of tasmania.dynamics.isentropic_prognostic.IsentropicPrognostic.step_integrating_vertical_advection:13: WARNING: Definition list ends without a blank line; unexpected unindent.
/tasmania/tasmania/dynamics/isentropic_prognostic.py:docstring of tasmania.dynamics.isentropic_prognostic.IsentropicPrognostic.step_integrating_vertical_advection:14: WARNING: Block quote ends without a blank line; unexpected unindent.
/tasmania/tasmania/dynamics/isentropic_prognostic.py:docstring of tasmania.dynamics.isentropic_prognostic.IsentropicPrognostic.step_integrating_vertical_advection:30: WARNING: Block quote ends without a blank line; unexpected unindent.
/tasmania/tasmania/dynamics/isentropic_prognostic.py:docstring of tasmania.dynamics.isentropic_prognostic.IsentropicPrognostic.step_integrating_vertical_advection:35: WARNING: Unexpected indentation.
/tasmania/tasmania/dynamics/isentropic_prognostic.py:docstring of tasmania.dynamics.isentropic_prognostic.IsentropicPrognostic.step_integrating_vertical_advection:48: WARNING: Unexpected section title.

Return
------
/tasmania/tasmania/dynamics/isentropic_prognostic.py:docstring of tasmania.dynamics.isentropic_prognostic.IsentropicPrognostic.step_integrating_vertical_advection:49: WARNING: Block quote ends without a blank line; unexpected unindent.
/tasmania/tasmania/dynamics/isentropic_prognostic.py:docstring of tasmania.dynamics.isentropic_prognostic.IsentropicPrognostic.step_neglecting_vertical_motion:8: WARNING: Unexpected section title.

Parameters
----------
/tasmania/tasmania/dynamics/isentropic_prognostic.py:docstring of tasmania.dynamics.isentropic_prognostic.IsentropicPrognostic.step_neglecting_vertical_motion:13: WARNING: Definition list ends without a blank line; unexpected unindent.
/tasmania/tasmania/dynamics/isentropic_prognostic.py:docstring of tasmania.dynamics.isentropic_prognostic.IsentropicPrognostic.step_neglecting_vertical_motion:14: WARNING: Block quote ends without a blank line; unexpected unindent.
/tasmania/tasmania/dynamics/isentropic_prognostic.py:docstring of tasmania.dynamics.isentropic_prognostic.IsentropicPrognostic.step_neglecting_vertical_motion:31: WARNING: Block quote ends without a blank line; unexpected unindent.
/tasmania/tasmania/dynamics/isentropic_prognostic.py:docstring of tasmania.dynamics.isentropic_prognostic.IsentropicPrognostic.step_neglecting_vertical_motion:41: WARNING: Unexpected section title.

Return
------
/tasmania/tasmania/dynamics/isentropic_prognostic.py:docstring of tasmania.dynamics.isentropic_prognostic.IsentropicPrognostic.step_neglecting_vertical_motion:43: WARNING: Block quote ends without a blank line; unexpected unindent.
/tasmania/tasmania/dynamics/diagnostics.py:docstring of tasmania.dynamics.diagnostics.IsentropicDiagnostics.__init__:4: WARNING: Unexpected section title.

Parameters
----------
/tasmania/tasmania/dynamics/diagnostics.py:docstring of tasmania.dynamics.diagnostics.IsentropicDiagnostics.__init__:16: WARNING: Block quote ends without a blank line; unexpected unindent.
/tasmania/doc/source/state.rst:5: WARNING: autodoc: failed to import function 'make_dataarray_3d' from module 'tasmania.utils.data_utils'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sphinx/util/inspect.py", line 169, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'tasmania.utils.data_utils' has no attribute 'make_dataarray_3d'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 665, in import_object
    obj = self.get_attr(obj, part)
  File "/usr/local/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 554, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/usr/local/lib/python3.5/site-packages/sphinx/util/inspect.py", line 185, in safe_getattr
    raise AttributeError(name)
AttributeError: make_dataarray_3d
/tasmania/tasmania/utils/data_utils.py:docstring of tasmania.utils.data_utils.get_state:4: WARNING: Field list ends without a blank line; unexpected unindent.
/tasmania/tasmania/utils/data_utils.py:docstring of tasmania.utils.data_utils.get_raw_state:4: WARNING: Field list ends without a blank line; unexpected unindent.
/tasmania/tasmania/utils/data_utils.py:docstring of tasmania.utils.data_utils.add:4: WARNING: Unexpected section title.

Parameters
----------
/tasmania/tasmania/utils/data_utils.py:docstring of tasmania.utils.data_utils.add:22: WARNING: Unexpected section title.

Return
------
/tasmania/doc/source/api.rst: WARNING: document isn't included in any toctree
/tasmania/doc/source/installation.rst:5: WARNING: unknown option: BRANCH
/tasmania/doc/source/installation.rst:13: WARNING: unknown option: docker/
/tasmania/doc/source/installation.rst:23: WARNING: unknown option: tasmania
/tasmania/doc/source/installation.rst:35: WARNING: unknown option: -v $PWD:/tasmania
/tasmania/doc/source/installation.rst:35: WARNING: unknown option: /tasmania
/tasmania/doc/source/installation.rst:35: WARNING: unknown option: --privileged -e DISPLAY -e XAUTHORITY:$XAUTHORITY -v /tmp/.X11-unix:/tmp/.X11-unix
/tasmania/doc/source/installation.rst:43: WARNING: unknown option: CONTAINER_ID
